name: Terraform Deploy

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"  # You can specify the Terraform version you want to use

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: infra

      # Validate the Terraform configuration
      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      # Apply the Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra
        env:
          TF_VAR_cloudflare_email: ${{ secrets.CLOUDFLARE_EMAIL }}
          TF_VAR_cloudflare_key: ${{ secrets.CLOUDFLARE_KEY }}
